import Head from 'next/head'
import styles from '../styles/Home.module.less'
import {Button, DatePicker} from 'component-lib'
// import {ContentBox } from '@nphc/nphc-ui-library'
// import { DatePicker } from '../components/Datepicker/DatePicker'
// import format from 'dayjs';

export default function Home() {
  return (
    <div className={styles['container']}>
      <Head>
        <title>Simple Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['main']}>
        {/* <ContentBox> */}
          <h1>
            <p>NEXT TEST APP!!!</p>
          </h1>
          <DatePicker/>
          <div style={{margineTop:"30px"}}>
            <Button label={'click me'}/>
          </div>
          {/* </ContentBox> */}
      </main>

      
    </div>
  )
}
